const SOCKET_EVENTS = {
  INCOMING: {
    JOIN_ROOM: "JOIN",
    SEND_OFFER: "SEND_OFFER",
    SEND_ANSWER: "SEND_ANSWER",
    LEAVE: "LEAVE",
    SEND_ICE_CANDIDATE: "SEND_ICE_CANDIDATE",
  },
  OUTGOING: {
    ROOM_CREATED: "ROOM_CREATED",
    ROOM_JOINED: "ROOM_JOINED",
    NEW_GUEST_JOINED: "NEW_GUEST_JOINED",
    OFFER: "OFFER",
    ANSWER: "ANSWER",
    BROADCAST: "BROADCAST",
    GUEST_LEFT: "GUEST_LEFT",
    ADD_ICE_CANDIDATE: "ADD_ICE_CANDIDATE",
  },
};

module.exports = { SOCKET_EVENTS };
